name: Update Event Schedule

on:
  schedule:
    - cron: "0 * * * *" # Runs at minute 0 of every hour (top of every hour)
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

permissions:
  contents: write # allow workflow to push changes

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper with logging
        run: |
          node scrape-wiki.js > scraper.log 2>&1 || (echo "Scraper failed"; cat scraper.log; exit 1)

      - name: Show scraper log
        run: cat scraper.log

      - name: Check events.json content
        run: cat events.json

      - name: Commit and push changes
        run: |
          git config user.name "autobot"
          git config user.email "autobot@example.com"
          git add events.json
          git commit -m "Update schedule" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dannihil/Wilderness-event-tracker.git
          git push origin main

      - name: List files to confirm output
        run: ls -lah

      - name: Check events.json content
        run: cat events.json || echo "events.json not found"
