name: Update Event Schedule

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm scrape-wiki.js exists
        run: ls -l scrape-wiki.js

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper with logging
        run: |
          echo "Starting scraper..."
          node scrape-wiki.js > scraper.log 2>&1 || (echo "Scraper failed"; cat scraper.log; exit 1)

      - name: List files to confirm output
        run: ls -lah

      - name: Check events.json content
        run: cat events.json || echo "events.json not found"

      - name: Configure Git
        run: |
          git config user.name "autobot"
          git config user.email "autobot@example.com"

      - name: Commit and push changes
        run: |
          git add events.json
          git commit -m "Update schedule" || echo "No changes to commit"
          git push
